# Generated by Django 4.0 on 2022-03-27 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='body',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='date_created',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='last_modified',
        ),
        migrations.AddField(
            model_name='todo',
            name='image',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='rent',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='todo',
            name='title',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
