# Generated by Django 4.0.4 on 2022-05-28 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0002_remove_todo_body_remove_todo_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='photo',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
