# Generated by Django 4.0.4 on 2022-06-08 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0003_todo_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='rent',
            new_name='collaborations',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='image',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='todo',
            name='title',
        ),
        migrations.AddField(
            model_name='todo',
            name='hour',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='photos',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='profile',
            field=models.ImageField(null=True, upload_to='profile_pics'),
        ),
        migrations.AddField(
            model_name='todo',
            name='state',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='todo',
            name='week',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
