# Generated by Django 4.0.4 on 2022-06-08 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Todo', '0005_postfeed'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='country',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
